### ISSUE TITLE
[BUG] Error 404 whenever a custom volume is specified

### ISSUE THREAD

**Issue by timkoers** [linuxserver/docker-unifi-controller#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I use a custom folder to map to the /config folder inside of the container, I get the 404 error whenever I try to reach the frontend.

I tried to set the permissions of the /config folder inside of the container to abc:abc but that didn't work.

### Expected Behavior

That the unifi-controller should just continue to boot and show the frontend.

### Steps To Reproduce

The permissions on the host filesystem are the same as the permissions for other containers and the other containers are working fine.

Whenever I uncomment `- '/mnt/ApplicationData/unifi-controller:/config'`, the unifi-controller frontend starts to work again

I've executed the `ls -al /` command and this is the output:
```bash
drwxr-xr-x   1 root root  4096 Dec 16 13:30 .
drwxr-xr-x   1 root root  4096 Dec 16 13:30 ..
drwxr-xr-x   1 abc  abc   4096 Dec 13 04:00 app
lrwxrwxrwx   1 root root     7 Mar 16  2022 bin -> usr/bin
drwxr-xr-x   2 root root  4096 Apr 15  2020 boot
drwxr-xr-x   2 root root 12288 Aug 29 20:09 command
drwxrwxrwx   1 root root     0 Dec 16 12:56 config
drwxrwxr-x   1 abc  abc   4096 Dec 13 03:59 defaults
drwxr-xr-x   5 root root   340 Dec 16 13:30 dev
-rwxr-xr-x   1 root root     0 Dec 16 13:30 .dockerenv
-rwxrwxr-x   1 root root 14022 Dec  6 04:47 docker-mods
drwxrwxr-x   1 root root  4096 Dec 16 13:30 etc
drwxr-xr-x   2 root root  4096 Apr 15  2020 home
-rwxr-xr-x   1 root root   907 Aug 29 20:09 init
lrwxrwxrwx   1 root root     7 Mar 16  2022 lib -> usr/lib
lrwxrwxrwx   1 root root     9 Mar 16  2022 lib32 -> usr/lib32
lrwxrwxrwx   1 root root     9 Mar 16  2022 lib64 -> usr/lib64
lrwxrwxrwx   1 root root    10 Mar 16  2022 libx32 -> usr/libx32
drwxr-xr-x   2 root root  4096 Mar 16  2022 media
drwxr-xr-x   2 root root  4096 Mar 16  2022 mnt
drwxr-xr-x   2 root root  4096 Mar 16  2022 opt
drwxr-xr-x   6 root root  4096 Aug 29 20:09 package
dr-xr-xr-x 351 root root     0 Dec 16 13:30 proc
drwx------   2 root root  4096 Mar 16  2022 root
drwxr-xr-x   1 root root  4096 Dec 16 13:30 run
lrwxrwxrwx   1 root root     8 Mar 16  2022 sbin -> usr/sbin
drwxr-xr-x   2 root root  4096 Mar 16  2022 srv
dr-xr-xr-x  13 root root     0 Dec 16 13:30 sys
drwxrwxrwt   1 root root  4096 Dec 16 13:30 tmp
drwxrwxr-x   1 root root  4096 Dec  6 04:46 usr
drwxr-xr-x   1 root root  4096 Mar 16  2022 var
```

Starting up the docker container and accessing the main page results in this log:

```bash
Starting unifi-controller ... done
Attaching to unifi-controller
unifi-controller    | [custom-init] No custom services found, skipping...
unifi-controller    | s6-rc: info: service s6rc-oneshot-runner: starting
unifi-controller    | s6-rc: info: service s6rc-oneshot-runner successfully started
unifi-controller    | s6-rc: info: service fix-attrs: starting
unifi-controller    | s6-rc: info: service 00-legacy: starting
unifi-controller    | s6-rc: info: service 00-legacy successfully started
unifi-controller    | s6-rc: info: service fix-attrs successfully started
unifi-controller    | s6-rc: info: service legacy-cont-init: starting
unifi-controller    | cont-init: info: running /etc/cont-init.d/01-envfile
unifi-controller    | cont-init: info: /etc/cont-init.d/01-envfile exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/01-migrations
unifi-controller    | [migrations] started
unifi-controller    | [migrations] no migrations found
unifi-controller    | cont-init: info: /etc/cont-init.d/01-migrations exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/10-adduser
unifi-controller    | usermod: no changes
unifi-controller    |
unifi-controller    | -------------------------------------
unifi-controller    |           _         ()
unifi-controller    |          | |  ___   _    __
unifi-controller    |          | | / __| | |  /  \
unifi-controller    |          | | \__ \ | | | () |
unifi-controller    |          |_| |___/ |_|  \__/
unifi-controller    |
unifi-controller    |
unifi-controller    | Brought to you by linuxserver.io
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | To support LSIO projects visit:
unifi-controller    | https://www.linuxserver.io/donate/
unifi-controller    | -------------------------------------
unifi-controller    | GID/UID
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | User uid:    911
unifi-controller    | User gid:    911
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | cont-init: info: /etc/cont-init.d/10-adduser exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/15-install
unifi-controller    | cont-init: info: /etc/cont-init.d/15-install exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/20-config
unifi-controller    | cont-init: info: /etc/cont-init.d/20-config exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/30-keygen
unifi-controller    | cont-init: info: /etc/cont-init.d/30-keygen exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/99-custom-files
unifi-controller    | [custom-init] No custom files found, skipping...
unifi-controller    | cont-init: info: /etc/cont-init.d/99-custom-files exited 0
unifi-controller    | s6-rc: info: service legacy-cont-init successfully started
unifi-controller    | s6-rc: info: service init-mods: starting
unifi-controller    | s6-rc: info: service init-mods successfully started
unifi-controller    | s6-rc: info: service init-mods-package-install: starting
unifi-controller    | s6-rc: info: service init-mods-package-install successfully started
unifi-controller    | s6-rc: info: service init-mods-end: starting
unifi-controller    | s6-rc: info: service init-mods-end successfully started
unifi-controller    | s6-rc: info: service init-services: starting
unifi-controller    | s6-rc: info: service init-services successfully started
unifi-controller    | s6-rc: info: service legacy-services: starting
unifi-controller    | services-up: info: copying legacy longrun unifi (no readiness notification)
unifi-controller    | s6-rc: info: service legacy-services successfully started
unifi-controller    | s6-rc: info: service 99-ci-service-check: starting
unifi-controller    | [ls.io-init] done.
unifi-controller    | s6-rc: info: service 99-ci-service-check successfully started
unifi-controller    | WARNING: An illegal reflective access operation has occurred
unifi-controller    | WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
unifi-controller    | WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
unifi-controller    | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
unifi-controller    | WARNING: All illegal access operations will be denied in a future release
```

**Notice that it isn't unpacking /app/unifi.deb**

Whenever I uncomment the volume and run the `ls -al /` command, this is the result
```bash
drwxr-xr-x   1 root root  4096 Dec 16 13:24 .
drwxr-xr-x   1 root root  4096 Dec 16 13:24 ..
drwxr-xr-x   1 abc  abc   4096 Dec 13 04:00 app
lrwxrwxrwx   1 root root     7 Mar 16  2022 bin -> usr/bin
drwxr-xr-x   2 root root  4096 Apr 15  2020 boot
drwxr-xr-x   2 root root 12288 Aug 29 20:09 command
drwxr-xr-x   5 abc  abc   4096 Dec 16 13:25 config
drwxrwxr-x   1 abc  abc   4096 Dec 13 03:59 defaults
drwxr-xr-x   5 root root   340 Dec 16 13:25 dev
-rwxr-xr-x   1 root root     0 Dec 16 13:24 .dockerenv
-rwxrwxr-x   1 root root 14022 Dec  6 04:47 docker-mods
drwxrwxr-x   1 root root  4096 Dec 16 13:25 etc
drwxr-xr-x   2 root root  4096 Apr 15  2020 home
-rwxr-xr-x   1 root root   907 Aug 29 20:09 init
lrwxrwxrwx   1 root root     7 Mar 16  2022 lib -> usr/lib
lrwxrwxrwx   1 root root     9 Mar 16  2022 lib32 -> usr/lib32
lrwxrwxrwx   1 root root     9 Mar 16  2022 lib64 -> usr/lib64
lrwxrwxrwx   1 root root    10 Mar 16  2022 libx32 -> usr/libx32
drwxr-xr-x   2 root root  4096 Mar 16  2022 media
drwxr-xr-x   2 root root  4096 Mar 16  2022 mnt
drwxr-xr-x   2 root root  4096 Mar 16  2022 opt
drwxr-xr-x   6 root root  4096 Aug 29 20:09 package
dr-xr-xr-x 358 root root     0 Dec 16 13:25 proc
drwx------   2 root root  4096 Mar 16  2022 root
drwxr-xr-x   1 root root  4096 Dec 16 13:25 run
lrwxrwxrwx   1 root root     8 Mar 16  2022 sbin -> usr/sbin
drwxr-xr-x   2 root root  4096 Mar 16  2022 srv
dr-xr-xr-x  13 root root     0 Dec 16 13:25 sys
drwxrwxrwt   1 root root  4096 Dec 16 13:25 tmp
drwxrwxr-x   1 root root  4096 Dec  6 04:46 usr
drwxr-xr-x   1 root root  4096 Mar 16  2022 var
```

Notice how the config folder has the abc:abc owners

This is the log of the startup of the container without the volume specified:

```bash
Recreating unifi-controller ... done
Attaching to unifi-controller
unifi-controller    | [custom-init] No custom services found, skipping...
unifi-controller    | s6-rc: info: service s6rc-oneshot-runner: starting
unifi-controller    | s6-rc: info: service s6rc-oneshot-runner successfully started
unifi-controller    | s6-rc: info: service fix-attrs: starting
unifi-controller    | s6-rc: info: service 00-legacy: starting
unifi-controller    | s6-rc: info: service fix-attrs successfully started
unifi-controller    | s6-rc: info: service legacy-cont-init: starting
unifi-controller    | cont-init: info: running /etc/cont-init.d/01-envfile
unifi-controller    | s6-rc: info: service 00-legacy successfully started
unifi-controller    | cont-init: info: /etc/cont-init.d/01-envfile exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/01-migrations
unifi-controller    | [migrations] started
unifi-controller    | [migrations] no migrations found
unifi-controller    | cont-init: info: /etc/cont-init.d/01-migrations exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/10-adduser
unifi-controller    | usermod: no changes
unifi-controller    |
unifi-controller    | -------------------------------------
unifi-controller    |           _         ()
unifi-controller    |          | |  ___   _    __
unifi-controller    |          | | / __| | |  /  \
unifi-controller    |          | | \__ \ | | | () |
unifi-controller    |          |_| |___/ |_|  \__/
unifi-controller    |
unifi-controller    |
unifi-controller    | Brought to you by linuxserver.io
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | To support LSIO projects visit:
unifi-controller    | https://www.linuxserver.io/donate/
unifi-controller    | -------------------------------------
unifi-controller    | GID/UID
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | User uid:    911
unifi-controller    | User gid:    911
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | cont-init: info: /etc/cont-init.d/10-adduser exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/15-install
unifi-controller    | *** installing unifi packages ***
unifi-controller    | Selecting previously unselected package unifi.
unifi-controller    | (Reading database ... 9373 files and directories currently installed.)
unifi-controller    | Preparing to unpack /app/unifi.deb ...
unifi-controller    | Unpacking unifi (7.3.76-19582-1) ...
unifi-controller    | Setting up unifi (7.3.76-19582-1) ...
unifi-controller    | invoke-rc.d: could not determine current runlevel
unifi-controller    | invoke-rc.d: policy-rc.d denied execution of start.
unifi-controller    | cont-init: info: /etc/cont-init.d/15-install exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/20-config
unifi-controller    | cont-init: info: /etc/cont-init.d/20-config exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/30-keygen
unifi-controller    | cont-init: info: /etc/cont-init.d/30-keygen exited 0
unifi-controller    | cont-init: info: running /etc/cont-init.d/99-custom-files
unifi-controller    | [custom-init] No custom files found, skipping...
unifi-controller    | cont-init: info: /etc/cont-init.d/99-custom-files exited 0
unifi-controller    | s6-rc: info: service legacy-cont-init successfully started
unifi-controller    | s6-rc: info: service init-mods: starting
unifi-controller    | s6-rc: info: service init-mods successfully started
unifi-controller    | s6-rc: info: service init-mods-package-install: starting
unifi-controller    | s6-rc: info: service init-mods-package-install successfully started
unifi-controller    | s6-rc: info: service init-mods-end: starting
unifi-controller    | s6-rc: info: service init-mods-end successfully started
unifi-controller    | s6-rc: info: service init-services: starting
unifi-controller    | s6-rc: info: service init-services successfully started
unifi-controller    | s6-rc: info: service legacy-services: starting
unifi-controller    | services-up: info: copying legacy longrun unifi (no readiness notification)
unifi-controller    | s6-rc: info: service legacy-services successfully started
unifi-controller    | s6-rc: info: service 99-ci-service-check: starting
unifi-controller    | [ls.io-init] done.
unifi-controller    | s6-rc: info: service 99-ci-service-check successfully started
unifi-controller    | WARNING: An illegal reflective access operation has occurred
unifi-controller    | WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
unifi-controller    | WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
unifi-controller    | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
unifi-controller    | WARNING: All illegal access operations will be denied in a future release
```

### Environment

```markdown
- OS: Ubuntu 22.04.01
- How docker service was installed: apt install docker docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
`docker-compose.yaml:`


  unifi-controller:
    container_name: unifi-controller
    restart: unless-stopped
    ports:
      - 3478:3478/udp
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
      - 6789:6789
      - 10001:10001/udp
    volumes:
      - '/mnt/ApplicationData/unifi-controller:/config'
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ='Europe/Amsterdam'
      - UNIFI_DB_NAME=unifi
 #     - PUID=1000
 #     - PGID=1000
    dns:
      - 1.1.1.1
      - 1.1.0.0
    image: linuxserver/unifi-controller



`sudo docker-compose up -d unifi-controller`
```

### Container logs

```bash
With the volume specified:

[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
s6-rc: info: service 00-legacy successfully started
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/15-install
cont-init: info: /etc/cont-init.d/15-install exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun unifi (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Without the volume specified:

[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
s6-rc: info: service 00-legacy successfully started
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/15-install
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 9373 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (7.3.76-19582-1) ...
Setting up unifi (7.3.76-19582-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
cont-init: info: /etc/cont-init.d/15-install exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun unifi (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
s6-rc: info: service 99-ci-service-check: stopping
s6-rc: info: service 99-ci-service-check successfully stopped
s6-rc: info: service legacy-services: stopping
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
s6-svwait: fatal: timed out
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service init-services: stopping
s6-rc: info: service 00-legacy: stopping
s6-rc: info: service init-services successfully stopped
s6-rc: info: service init-mods-end: stopping
s6-rc: info: service 00-legacy successfully stopped
s6-rc: info: service init-mods-end successfully stopped
s6-rc: info: service init-mods-package-install: stopping
s6-rc: info: service init-mods-package-install successfully stopped
s6-rc: info: service init-mods: stopping
s6-rc: info: service init-mods successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by olineham** [comment]
I had a similar problem until I moved the volume to an ext4 filesystem instead of ntfs. The clue was looking in config/logs/mongodb.log of the volume mount and seeing that mongodb was repeatedly crashing.

What is the underlying filesystem type of your /mnt/ApplicationData?

**Comment by timkoers** [comment]
Well, it started to work. I guess it needed around a week to do something? 

The underlaying filesystem is ext4.

**Comment by LukasKnuth** [comment]
I'm having the same issue on my system as well. I run the container via Kubernetes.

If I open the frontend, HTML pages serve correctly, but opening the Network console in FireFox shows every XHR request it makes is a 404.

* I'm running this on a Raspberry Pi 4 with NixOS as the underlying system. The underlying filesystem is ext4.
* The `/config` folder is owned by `abc:abc`, so are all folders/files _inside_

Here is the full log of the container:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/15-install
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 9470 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (7.3.76-19582-1) ...
Setting up unifi (7.3.76-19582-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
cont-init: info: /etc/cont-init.d/15-install exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun unifi (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Any ideas?

**Comment by LukasKnuth** [comment]
Apologies, my occurrence of the 404 problem could be traced back to a faulty Traefik configuration.

I had the Dashboard mounted on the default `matchRule`, which seemed to catch all relative XHR/AJAX requests. I found this using Traefiks access log.

The container was performing fine and now that the routing issue is resolved, everything seems to be working as expected

**Comment by timkoers** [comment]
The issue is back. 
I tried upgrading the container, database migration showed up for 2 days and nothign happened.

Then I've renamed the data folder so that the controller is resetted and the 404 is back.
